### ISSUE TITLE
Disk decryption focus is wrong on second visit

### ISSUE THREAD

**Issue by brs17** [pop-os/installer#128]
**Issue/Bug Description:**
When initially selecting the decryption pop-over, the focus is on the password field (which is expected/good). Moving away from this pop-over and then revisiting it, the focus is on the sentence of text and not the password (bad, see below).

![broken](https://user-images.githubusercontent.com/7460774/40378043-a6dc1868-5daf-11e8-93f0-c6688a7d1629.png)

**Comment by cassidyjames** [comment]
Looks like we need to connect switching to the Decrypt view to focusing the Password entry. Should be simple.
