### ISSUE TITLE
If `Try Demo Mode` is selected at all, this code path executes

### ISSUE THREAD

**Issue by brs17** [pop-os/installer#163]
**Distribution (run `cat /etc/os-release`):**
 18.04 and 18.10
 
 **Issue/Bug Description:**
At `Try or Install Pop!_OS` page of the installer, if `Try Demo Mode` is selected but the next button is not pressed and then another option is selected and `Next` is pressed, the installer closes as `Try Demo Mode` code was executed.

**Comment by brs17** [comment]
I just tried this on the iso 14 (built last night) and it still happens.

**Comment by mmstick** [comment]
I keep forgetting this is fixed in #157.

**Comment by brs17** [comment]
Could you potentially pull it out of there and make it it's own pr? :smile:

**Comment by mmstick** [comment]
Working on it.

**Comment by brs17** [comment]
Awesome @mmstick ! Good work. The pr looks good to me, just waiting for code review.

**Comment by brs17** [comment]
Fixed in #164
