### ISSUE TITLE
Update installer help on EFI partition size

### ISSUE THREAD

**Issue by thomas-zimmerman** [pop-os/installer#175]
**Distribution (run `cat /etc/os-release`):**
 18.04, 18.10
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
installer

**Issue/Bug Description:**
![screenshot from 2019-01-21 19-34-57](https://user-images.githubusercontent.com/41023059/51495394-5f61bd00-1d79-11e9-969e-6e2e8d1672ed.png)
EFI partition was created with 256MiB in size, installer states 256MiB is minimum but enforces a 500MiB minimum

**Steps to reproduce (if you know):**
run installer

**Expected behavior:**
installer help text matches enforced minimums

**Other Notes:**

**Comment by mmstick** [comment]
Seems the installer has this set:

```vala
const uint64 REQUIRED_EFI_SECTORS = 524288;
```

Where 524288 / 2 / 1024 does indeed equal 256 MiB, so the text is still valid.

It's likely that their partition was a few sectors shorter than the minimum requirement.

Though it's still better to recommend 500 MiB, since that's what a default install uses.
