### ISSUE TITLE
Support recovery shell for upgrades

### ISSUE THREAD

**Issue by brs17** [pop-os/installer#184]
Support a recovery shell that appears during the upgrade, to attempt to fix the upgrade.

**Comment by cassidyjames** [comment]
I know the UX has greatly diverged from the original/upstream design, but the original idea here is that failures would give an option to boot into the live session, which would allow all recovery options. I.e. Googling something in the web browser, inspecting the filesystem from Files, using Terminal, using any included partitioning tools, etc.

**Comment by mmstick** [comment]
In Pop's case, you're already in a live session, so all that needs to be done is to open a terminal, and maybe automatically open some offline documentation to help step through possible steps.

**Comment by brs17** [comment]
Current plan is to continue with the systemd upgrade process and add additional functionality to the recovery partition as needed.
