### ISSUE TITLE
How to install without bootloader

### ISSUE THREAD

**Issue by MayusYT** [pop-os/installer#191]
(This is a crosspost because people told me to post it here)
Hi,
I currently want to install Pop!_OS (which apparently uses this installer) on an SSD that already has the Clover bootloader with a Grub EFI file on it. I already got ubuntu to boot with that setup.

Because I heard that this installer automatically installs systemd-boot, I'm kinda worried that this will overwrite my current bootloader setup. When I select my current bootloader partition (with clover/grub on it), it says that it's too small. Is there a way to let the installer completely ignore the bootloader?

mmstick on the elementary repo told me that it won't overwrite my current bootloader, but I don't really want to risk it as I had a bad experience when installing ubuntu.

Isn't there a command line argument like for the ubiquity installer?

Thanks in advance!

**Comment by jackpot51** [comment]
There is a command line installer, `distinst`. This is out of scope for our graphical installer

**Comment by mmstick** [comment]
As mentioned in the elementary repository, the installation of an EFI bootloader on any system will not overwrite the installation of any other bootloader installed on the system. The EFI specification allows for multiple bootloaders to be installed simultaneously, or even multiple EFI partitions.

So you would be able to select between Pop!_OS's systemd-boot bootloader and any other bootloader installed on the system. If you aren't able to resize your EFI partition, you can always create a second EFI partition.
