### ISSUE TITLE
19.10: Clean install description splits Pop!_OS to two lines

### ISSUE THREAD

**Issue by brs17** [pop-os/installer#200]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.10

**Issue/Bug Description:**
On the description test for a `Clean Install` `Pop!_OS` is split up into `Pop!` and `_OS` across two different lines. This should all be on the same line.
![Screenshot from 2019-10-11 00-57-29](https://user-images.githubusercontent.com/7460774/66616910-e5d06000-eb8f-11e9-892a-70f9cc02f21f.png)

**Comment by mmstick** [comment]
Possibly happened because of padding changes in the theme. GTK doesn't consider `_` as being part of a word when it does its word wrapping, so it splits at the `_` to the next line. We could increase the width of the window slightly so that it doesn't wrap.

**Comment by cassidyjames** [comment]
The correct solution that doesn't depend on the theme never changing (and should work across translations) is to use Unicode word-joiner character between the `!` and `_`. This will prevent it from breaking in GTK.
