### ISSUE TITLE
20.04: Intel debug iso #5 boots to recovery partition by default after install

### ISSUE THREAD

**Issue by leviport** [pop-os/installer#210]
Installation seems to go fine, but after it reboots, it boots into the recovery partition. If I reboot and look at the systemd-boot menu, the entries are in the order I would expect, except the recovery partition is highlighted. There is no `=>` icon indicating a default entry. I can use the <kbd>d</kbd> key to override this for the normal installation, but if I clear the default setting again with <kbd>d</kbd>, it starts booting back into the recovery partition.

**Comment by jackpot51** [comment]
It looks like systemd-boot now requires loader.conf default entries to be the filename including extension, such as `Pop_OS-current.conf`

**Comment by jackpot51** [comment]
Workaround in https://github.com/pop-os/systemd/commit/ddb09573ebb7264538af3f77f16b5d1c252a8551
