### ISSUE TITLE
Encrypt Swap Partition

### ISSUE THREAD

**Issue by WereDev** [pop-os/installer#213]
It would be great if upon selecting to encrypt the drive, it would also encrypt the swap partition.  Things that are in memory are often written to the swap partition, especially when you go into suspend or hibernate.  This means that things, like encryption keys, network credentials, anything that might be sensitive and in memory, will be written to the swap partition and not encrypted.  This pretty much negates the security gained by encrypting the main drive.

**Comment by mmstick** [comment]
The swap partition is encrypted. Check your `/etc/crypttab` and compare with `/proc/swaps`

**Comment by WereDev** [comment]
My apologies.  I didn't see a LUKS chain so I didn't think it was encrypted.  I will read up more on this.

Thank you.
