### ISSUE TITLE
"Try Demo Mode" hidden behind setting Lang and keyboard layout

### ISSUE THREAD

**Issue by thomas-zimmerman** [pop-os/installer#215]
**Distribution (run `cat /etc/os-release`):**
Pop!OS 

**Issue/Bug Description:**
Installer can not be closed by "close" button on window and "Try Demo Mode" button not available to use until the Language and Keyboard layout has been chosen. 

**Other Notes:**

**Comment by cassidyjames** [comment]
The demo mode part was by design upstream; we did not want a case where the user was getting a non-translated UI with the wrong keyboard layout as a demo.
