### ISSUE TITLE
Refresh Install does not appear for LUKS encrypted installs

### ISSUE THREAD

**Issue by cwestkaemper** [pop-os/installer#217]
I am running Pop os 20.10 (originally installed as 20.04 and then upgraded)
 

When you boot into a live image/recovery partition for pop os, after picking your language/keyboard configuration you are presented with 2 options- Use Entire Disk and Custom Install. A prompt appears at the top of the installer window to unlock the encrypted partition to "enable more options". However, unlocking the partition does not make the "refresh install" option appear. On unencrypted installs, it appears by default.

I expect the intended behaviour is that the refresh install option becomes available after the encrypted partition is unlocked, but nothing happens.

**Comment by leviport** [comment]
I can't seem to replicate this behavior. After unlocking the encrypted partition, I always see the Refresh Install button appear. Can you give us some details about your installation? Is it installed in UEFI mode or legacy BIOS mode?

**Comment by cwestkaemper** [comment]
It is installed in UEFI mode.

At first I thought the issue was the fact that the recovery image was still on 20.04, but running off a 20.10 liveimage did not solve the issue either.

**Comment by mmstick** [comment]
Are you refreshing from an ISO of the same release? You can't refresh with a different release.

**Comment by cwestkaemper** [comment]
As I said, I thought that was the issue, because the recovery image IS the wrong release, but trying a 20.10 live image did not fix the issue either.

**Comment by jacobgkau** [comment]
I'm able to replicate this. It's a 20.10 installation, installed from a 20.10 iso with the standard partition layout and full-disk encryption. Booting to the 20.10 Recovery partition and unlocking the drive does not give me a Refresh option:

![Screenshot from 2021-02-18 22-18-31](https://user-images.githubusercontent.com/7199422/108429022-b0fd0000-71fc-11eb-95ae-2daef079071c.png)

In the Files app, I can see that the encrypted volume was successfully unlocked (but not automatically mounted.)

**Comment by jacobgkau** [comment]
This will be closed by https://github.com/pop-os/distinst/pull/251.
