### ISSUE TITLE
21.04: Refresh Install fails and leaves previously working installation unbootable

### ISSUE THREAD

**Issue by leviport** [pop-os/installer#224]
**Distribution (run `cat /etc/os-release`):**
Pop!\_OS 21.04 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Installer

**Issue/Bug Description:**
If I perform a clean 21.04 off the latest debug iso (number 11), then boot into recovery and try to refresh the install, it will fail and break my install. When it fails, the status bar shows "Extracting files... 100%". I've seen it happen on both encrypted and unencrypted installs.

Here are logs from an instance where this happened: [installer.log](https://github.com/pop-os/installer/files/6719008/installer.log)

**Steps to reproduce (if you know):**
- Install 21.04 from latest debug iso
- Reboot into recovery
- Refresh installation

**Expected behavior:**
Refresh the installation

**Other Notes:**
Tested the Intel/AMD iso on lemp9 and mira-b1

**Comment by jacobgkau** [comment]
With the latest 21.04 iso, I tried a refresh install twice. The first time, the installer closed. After rebooting, I started the installer from the terminal the second time, and it didn't close, but showed the failure screen. Here's the terminal output:

```
[INFO distinst:src/auto/options/mod.rs:48] found OS on "/dev/dm-1": Linux (Pop!_OS 21.04)
[INFO distinst:src/auto/options/mod.rs:67] found refresh option on "/dev/dm-1"
[DEBUG distinst:crates/disk-types/src/sector.rs:17] get block size for "/sys/class/block/dm-1"
[ERROR distinst:ffi/src/os.rs:55] DistinstOsRelease field was to be destroyed even though it is null
[ERROR distinst:ffi/src/os.rs:55] DistinstOsRelease field was to be destroyed even though it is null
[ERROR distinst:ffi/src/os.rs:55] DistinstOsRelease field was to be destroyed even though it is null
[ERROR distinst:ffi/src/os.rs:55] DistinstOsRelease field was to be destroyed even though it is null
[ERROR distinst:ffi/src/os.rs:55] DistinstOsRelease field was to be destroyed even though it is null
[ERROR distinst:ffi/src/os.rs:55] DistinstOsRelease field was to be destroyed even though it is null
[ERROR distinst:ffi/src/os.rs:55] DistinstOsRelease field was to be destroyed even though it is null
[ERROR distinst:ffi/src/os.rs:55] DistinstOsRelease field was to be destroyed even though it is null
[ERROR distinst:ffi/src/os.rs:55] DistinstOsRelease field was to be destroyed even though it is null
[ERROR distinst:ffi/src/os.rs:55] DistinstOsRelease field was to be destroyed even though it is null
[INFO distinst:src/auto/options/apply.rs:237] applying refresh install config
[ERROR distinst:ffi/src/auto.rs:597] failed to apply install option: EFI partition is required, but not found on this option
```

**Comment by jacobgkau** [comment]
Fixed by https://github.com/pop-os/installer/pull/226.

Any beta users who attempted to refresh before this fix will need to back up their files and reinstall, as the failed refresh breaks it beyond what a refresh would repair.
