### ISSUE TITLE
Make checkbox selected by default on the Drive Encryption screen.

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/installer#232]
The checkbox for "Encryption password is the same as user account password." might be better checked by default to save people a click.
![Installer-encryption](https://user-images.githubusercontent.com/57502897/133815889-9230dbdc-2865-47fa-8e94-e2dab5d15184.png)

**Comment by WatchMkr** [comment]
With this change, the "Encrypt" button would be active and the default suggested action.

**Comment by maria-komarova** [comment]
Right, made the change in the mockup to reflect it:
![Installer-encryption](https://user-images.githubusercontent.com/57502897/133818207-a84369ff-42c8-458c-9df5-80574f8424e1.png)
