### ISSUE TITLE
Updated designs for Refresh Install process initiated from the Recovery Partition.

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/installer#233]
The changes in the designs intended to streamline the Refresh OS process. The changes would also help better align the process with Refresh OS initiated from the Settings panel visually.

The chart below might help to figure out what we can show in the UI depending on things like bootloader entry, weather the Refresh OS is actually possible after decryption, and how many partitions are present. 
![FlowChart](https://user-images.githubusercontent.com/57502897/133817719-cff82996-b87a-4394-9686-a8626f530611.png)

To summarize, there are four scenarios:
1. There is a bootloader entry and Refresh OS is possible.
2. There is a bootloader entry but there is no Pop!_OS installed. There are multiple partitions.
3. There is a bootloader entry but there is no Pop!_OS installed. There is only one partition - main difference is that there is no “Select another partition” button in this view (see mockups for more context):
![Installer-user-account-name (2)](https://user-images.githubusercontent.com/57502897/133821678-74af2c08-aa83-461d-8fc4-99bbe6c1d6df.png)
4. There is no bootloader entry.

The mockups could be clicked through here (use side panel on the left to switch between the four outlines scenarios: https://www.figma.com/proto/xdEDKxKMRHrdN0tMqsQm0h/Refresh-Install?node-id=16%3A538&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=16%3A538&show-proto-sidebar=1
In addition, this is another way to look at the mockups: https://www.figma.com/file/xdEDKxKMRHrdN0tMqsQm0h/Refresh-Install?node-id=0%3A1

**Comment by WatchMkr** [comment]
Note that the top bar and some panel copy changes depending on if a Pop!_OS bootloader is present (which suggest refresh is a possible option).
