### ISSUE TITLE
Change the default user account Avatar

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/installer#235]
Artwork incoming

**Comment by jacobgkau** [comment]
Related: https://github.com/pop-os/installer/issues/221

**Comment by maria-komarova** [comment]
Passing the image on, here is the 512x512 png. Can also do other formats, just let me know. 
![default-avatar](https://user-images.githubusercontent.com/57502897/142299058-ebf92ccd-dd8b-4ed4-96d3-ca5fc882529c.png)
Mockup inside the Create User Account. 
![Installer-user-account-name (11)](https://user-images.githubusercontent.com/57502897/142299192-8db9b1ab-029a-4fe5-927d-a5da154ee822.png)

**Comment by mmstick** [comment]
Since the image has to exist on the file system post-install, should this be added to `pop-desktop`?
