### ISSUE TITLE
[24.04 w/ COSCMIC] A boot entry is added automatically by systemd

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/installer#288]
Need to patch out of systemd.

**Comment by jackpot51** [comment]
Potentially fixed in https://github.com/pop-os/systemd/commit/6ffa946989c6a633e51a4fedaf5a78bb46c9c2d0

**Comment by WatchMkr** [comment]
This does not appear to be fixed in the 137 debug ISO

**Comment by jackpot51** [comment]
It looks like that commit failed to build.

**Comment by jackpot51** [comment]
The change was improved in https://github.com/pop-os/systemd/commit/50f212a79959cb763a1f76cbd449ccc9934ed871.

**Comment by jackpot51** [comment]
When the master_noble branch of systemd finally builds, this should be fixed. I've had a few build issues that should now be sorted out.

**Comment by jackpot51** [comment]
I have checked that this is resolved in my own local build of the 24.04 ISO.
