### ISSUE TITLE
StorageBar widget structure

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/installer#29]
There are still a few things screwy with the widget structure, making its themability in stylesheets broken.

For example, this is a Granite.StorageBar in the elementary stylesheet:

![screenshot from 2018-04-04 09-09-44](https://user-images.githubusercontent.com/611168/38316831-e226e264-37e8-11e8-8638-54488922478f.png)

This is master as of right now, also in the elementary stylesheet (ignore the titlebar, since I had not restarted Shell):

![screenshot from 2018-04-04 09-09-57](https://user-images.githubusercontent.com/611168/38316851-eca1a29c-37e8-11e8-967a-56e041d1fe73.png)

It looks like we're manually setting styling on the widget in the installer instead of leaning on the system stylesheet, and it looks like the actual structure of the widgets might not match what the stylesheet expects.

The Vala source for Granite.StorageBar is available at https://github.com/elementary/granite/blob/master/lib/Widgets/StorageBar.vala. You can also compile Granite locally and run `granite-demo`, then use the GTK inspector to look at the widget structure and classes.

If we need to add borders, that should be done in the Pop! stylesheet, as that's not a generic style that will work across other stylesheets.

**Comment by mmstick** [comment]
Beyond setting padding back to 0 and using the `trough` class on the disk bar (in addition to the file system-specific coloring), there's not any styling being done to the widget.
