### ISSUE TITLE
Custom Partitioning should ignore small unused space

### ISSUE THREAD

**Issue by isantop** [pop-os/installer#45]
The custom partitioning view should be ignoring small amounts of unused space (typically at the end of a drive). This would simplify the layout and prevent showing things which are too small to be of use when installing Pop!_OS.

**Comment by mmstick** [comment]
The current issue is that partitions that are too small are making the disk bar longer than it should be, which makes the other disk bars grow to a larger size, and makes the unused space appear larger than it actually is. I have an idea to fix this.
