### ISSUE TITLE
Custom partitioning reformatting issue

### ISSUE THREAD

**Issue by brs17** [pop-os/installer#53]
On the custom partitioning screen, I reformat a drive, creating a 512MB partition for the efi partition(formatted `fat32`), a 4GB swap partition(formatted `linux-swap`), and with the remainder of the space on the drive a partition which I format as `lvm2 pv`. 

After applying the changes in Gparted, I went back to the installer and saw this(looking at the Samsung SSD 850):
![screenshot from 2018-04-09 17-53-04](https://user-images.githubusercontent.com/7460774/38514880-aad40c8c-3bef-11e8-920d-6fed14f02cfb.png)

I go ahead and properly set up the /boot/efi partition and swap partitions.

The root partition looks like this: 
![screenshot from 2018-04-09 17-53-32](https://user-images.githubusercontent.com/7460774/38515039-31fe9cfe-3bf0-11e8-8e1b-2e13aeecf75c.png)

Once I run the installation, I see an error: ```log info: install error: root partition does not have a file system``` and the installer seems to just be hanging. 
![screenshot from 2018-04-09 17-53-57](https://user-images.githubusercontent.com/7460774/38515077-59e7891a-3bf0-11e8-9785-f9bc5faaf60f.png)

**Comment by mmstick** [comment]
PR coming soon to fix this. Just would like to review some things first before I submit the PR.
