### ISSUE TITLE
Front-end handling preseeding

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/installer#7]
Cassidy and elementary to work together on this.

**Comment by cassidyjames** [comment]
I believe this is done in the shipping installer?

**Comment by brs17** [comment]
Seeing that @sarahpandabeara nor @mmstick know what exactly this issue was for, I'm closing it.

**Comment by rgl** [comment]
can you please reopen this? or do you prefer a new issue?

for more details see https://github.com/pop-os/iso/issues/352

**Comment by mmstick** [comment]
@rgl We will develop a new installer for COSMIC soon.

**Comment by rgl** [comment]
@mmstick, will it include some kind of automated installation along the lines of https://github.com/pop-os/iso/issues/352? do you have some kind of issue for this already?

**Comment by jacobgkau** [comment]
@rgl The issue for that feature request is the one you're linking.
