### ISSUE TITLE
Windows are still not the same size

### ISSUE THREAD

**Issue by brs17** [pop-os/installer#70]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please start a conversation in our chat https://chat.pop-os.org/ or post on our subreddit https://reddit.com/r/pop_os - as these are the proper forums for those types of posts.

**Issue/Bug Description**
Drive selection view is larger than the previous windows.

@cassidyjames and I looked at this:

The heading label "Select a drive to use for installation" is too wide which is causing the entire window to widen.
It should be fixed by setting a max width on that label and having it wrap which would also help with longer translations such as German.

**Comment by WatchMkr** [comment]
We just discussed this text :-). We're going to move to "Select a drive". I think the longer string was due to the old layout.
