### ISSUE TITLE
Image missing during installation

### ISSUE THREAD

**Issue by brs17** [pop-os/installer#80]
**Distribution - (run ```cat /etc/os-release```)**
 18.04 debug 8 (both intel and nvidia)
 
**Issue/Bug Description**
Image is missing during the actual installation(progress bar page) of Pop!_OS. A Pop!_OS logo is showed instead.

**Expected behavior**
Rocket image heading to new planet should be shown

**Comment by jackpot51** [comment]
Fixed by 8c8a8bc0cb376229c5370556dbec15f3fe2d95bf
