### ISSUE TITLE
Galp3 and oryp3-b failed to install

### ISSUE THREAD

**Issue by brs17** [pop-os/installer#83]
**Distribution - (run ```cat /etc/os-release```)**
 18.04 testing iso debug 8
 
**Issue/Bug Description**
@djordan2 went through an installation on a galp3 attempting to do custom partitioning.

The installation failed and the following logs are from the installer:

[galp3_imaging_log_custom_batter.log](https://github.com/pop-os/installer/files/1900564/galp3_imaging_log_custom_batter.log)

Selecting to "Format" all drives in the dropdown seemed to fix the issue.

---------------------------------

I also had an installation fail when trying to install on the oryp3-b. This happened right after trying to wipe and create custom partitioning on the drive in the machine (right after doing this: #82). The logs from this installation:

[oryp3_installation_failed.log](https://github.com/pop-os/installer/files/1900849/oryp3_installation_failed.log)

I tried rebooting and trying the installer again. The same problem arose. Finally rebooting another time, and the installation was successful.

**Comment by mmstick** [comment]
Some kind of issue with `bootctl`?

> ERROR: bootloader error: bootctl failed with status: exit code: 1

**Comment by brs17** [comment]
Looks like it, my thought for recreating the issue would be to run the installer with `RUST_BACKTRACE=1`. Did you have an idea for what to do to figure out what went/goes wrong?

**Comment by brs17** [comment]
Just had it happen again on the oryp3-b. Ran `sudo RUST_BACKTRACE=1 io.elementary.installer`.
This is on the debug#9 iso (one Jeremy made this afternoon)

[backtrace.log](https://github.com/pop-os/installer/files/1900996/backtrace.log)

**Comment by brs17** [comment]
I can confirm that tagging the partitions with the "format" toggle fixes the issue.

**Comment by mmstick** [comment]
The `RUST_BACKTRACE` part won't help since the issue is not a panic in Rust code. It seems that the `bootctl` command is failing for some reason, but these logs don't include the stderr outputs that `bootctl` may have written the reason for failure to. I'll see if I can replicate it.

**Comment by jackpot51** [comment]
@brs17 I need your `journalctl` when this happens

**Comment by brs17** [comment]
Not getting much with journald logs:

[journald.log](https://github.com/pop-os/installer/files/1904156/journald.log)

**Comment by brs17** [comment]
[journalctl.log](https://github.com/pop-os/installer/files/1904478/journalctl.log)

Here you go!

**Comment by brs17** [comment]
fat32

**Comment by brs17** [comment]
Installation normally works if I toggle the "Format" buttons. (but doesn't force it by default to "format" itself since it already is fat32 (made in gparted)

**Comment by jackpot51** [comment]
Interesting

**Comment by mmstick** [comment]
Managed to get this to fail by creating a 500MiB Fat32 partition in gparted, then attempting to install to it without formatting.

```
/dev/sdb1: UUID="E1F9-7DA3" VERSION="FAT32" TYPE="vfat" USAGE="filesystem" PART_ENTRY_SCHEME="gpt" PART_ENTRY_UUID="d65f0531-bb2a-4989-bfac-1728c52bb171" PART_ENTRY_TYPE="ebd0a0a2-b9e5-4433-87c0-68b6b72699c7" PART_ENTRY_NUMBER="1" PART_ENTRY_OFFSET="2048" PART_ENTRY_SIZE="1024000" PART_ENTRY_DISK="8:16"
```

The `PART_ENTRY_TYPE` is a `basic data partition`, rather than a `efi` partition.

**Comment by mmstick** [comment]
@brs17 I've just pushed a change to `distinst` which seems to have fixed the issue for me.

**Comment by brs17** [comment]
This looks fixed in the latest build. Going to close.
