### ISSUE TITLE
UX oddity from employee testing

### ISSUE THREAD

**Issue by brs17** [pop-os/installer#88]
**Distribution - (run ```cat /etc/os-release```)**
18.04 testing isos 
 
**Issue/Bug Description**
I had a number of people around the office try out the installer (all people who had not seen the installer previously). Overall feedback was rather positive! 

There was a little bit of hesitation when seeing "Cancel installation" when all the user wanted to do was go back a step. 

@cassidyjames  I know this has been discussed at lengths here: https://github.com/elementary/installer/issues/295 but I wanted to share the feedback regardless.

**Comment by jsmestad** [comment]
I found the same thing - https://www.reddit.com/r/pop_os/comments/8c2mbq/pop_os_1804_testing_release_call_for_testing/dxez9s1/?utm_content=permalink&utm_medium=front&utm_source=reddit&utm_name=pop_os

**Comment by cassidyjames** [comment]
@brs17 do you recall which step exactly? Each step can be set as either cancellable or to go back to the previous step.

**Comment by cassidyjames** [comment]
@jsmestad I understand that part, but I was wondering if he recalled which of the views this was talking about specifically. There are multiple places "Cancel Installation" appears. The Custom Partitioning view was addressed in this PR https://github.com/elementary/installer/pull/317, so if that was it, we could merge that in and close this issue. If it was a different view, we should identify it and keep this issue open.

**Comment by jsmestad** [comment]
Ah ok sorry about that :)

**Comment by brs17** [comment]
This was in regards to the Custom Partitioning view which has been addressed here: https://github.com/pop-os/installer/issues/97
