### ISSUE TITLE
Custom partitioning confusion from internal employee testing

### ISSUE THREAD

**Issue by brs17** [pop-os/installer#89]
**Distribution - (run ```cat /etc/os-release```)**
Pop!_OS 18.04 debug isos # 9,10

**Issue/Bug Description**
I had a few people around the office try the installer (people who had never seen it before). One person who attempted the custom partitioning pointed out/stated that the screen is not super intuitive, since clicking on the drive bar is required to set certain things, while the "modify partitions" is required for others.

**Comment by mmstick** [comment]
You can also click on a drive's label. It was pointed out to me that highlighting a drive when the mouse hovers over a partition box would help to point out which label belongs to what partition.

**Comment by cassidyjames** [comment]
We can also use tooltips to provide a bit of an extra hint, like "Select to use partition" or something

**Comment by cassidyjames** [comment]
Tooltip bit tracked upstream: https://github.com/elementary/installer/issues/315

**Comment by cassidyjames** [comment]
I think I'm going to close this issue since there's no individually-actionable items here. We've since added better help text onto the view itself, plus we have the tooltip issue reported and tracked elsewhere. Let me know if I'm wrong and we can re-open this.
