### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/installer#9]
Discuss what elementary's new installer process looks like. Decide if we can utilize the work they've done or if we need to move forward with Gnome Initial Setup.

Cassidy and elementary to work together on this.

**Comment by sarahpandabeara** [comment]
Jeremy likes what Dan has but whether or not we implement this will depend on whether or not the work will be complete with enough time to implement in 18.04

**Comment by cassidyjames** [comment]
I think it might make sense to punt this for Pop! until after 18.04. Even if the elementary one is "done" in time, elementary online accounts privacy, etc. might be different from what we have in GNOME, so it would probably require downstream patches and more work
