### ISSUE TITLE
Terminal install progress expands the installer window

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/installer#96]
![screenshot from 2018-04-23 01-01-55](https://user-images.githubusercontent.com/3430283/39102298-025daa2e-4692-11e8-8720-c9145ab5f347.png)

**Comment by cassidyjames** [comment]
Previously reported upstream at https://github.com/elementary/installer/issues/257

**Comment by brs17** [comment]
This was fixed with https://github.com/pop-os/installer/pull/108
