### ISSUE TITLE
Custom partitions screen should have "Back" button rather than "Cancel Installation"

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/installer#97]
Back button would move the user to the Select a Drive window.

![screenshot from 2018-04-23 01-22-11](https://user-images.githubusercontent.com/3430283/39102564-c838716e-4694-11e8-8b2e-1048adf6eab9.png)

**Comment by jackpot51** [comment]
This should be easy to do. The same thing applies to the disk selection screen, I imagine

**Comment by brs17** [comment]
Similar suggestion posted in an earlier issue: https://github.com/pop-os/installer/issues/88

**Comment by cassidyjames** [comment]
It now says back, but it's still going to Try or Install. Fixing…
