### ISSUE TITLE
Attempting to decrypt a partition failed and locked up the installer

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/installer#98]
![screenshot from 2018-04-23 01-25-49](https://user-images.githubusercontent.com/3430283/39102676-95582e78-4695-11e8-9f42-db8794a9fd05.png)

**Comment by jackpot51** [comment]
Interesting. This area of the installer has probably not been heavily tested, and will need refinement

**Comment by mmstick** [comment]
It's a timing issue. When you decrypt a LUKS partition, it can take several seconds for the LVM device, and each of its partitions, to be initialized.

**Comment by WatchMkr** [comment]
A force quit or wait dialog pops up. The window is frozen even after choosing to wait multiple times. I've used the feature previously and something is different.

**Comment by mmstick** [comment]
I've pushed a commit to distinst which has fixed this.
