### ISSUE TITLE
Custom Partitions decrypt popover is unclear

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/installer#99]
* It's unclear why the volume must be decrypted. 
* "Password" tip is not present until moving to the second Volume Name field so the user doesn't know what they're supposed to put into the field.
* What should go in Volume Name is unclear.

**Comment by cassidyjames** [comment]
One easy fix is that we shouldn't be using hint text for required UI copy; GTK only displays it when the entry is unfocused. Instead, let's switch it to the `Label: Entry` format we use elsewhere.

@mmstick what is supposed to go into Volume Name?

**Comment by mmstick** [comment]
The volume name can be anything. LUKS and LVM devices have to be assigned a name when they are opened.

**Comment by WatchMkr** [comment]
So we can just name it ourselves so the user doesn't need to?

**Comment by cassidyjames** [comment]
@WatchMkr yeah I was wondering if that's sane or not. I _think_ it is, but I'm also fine prefilling a sane default. I also think providing a more dialog-style layout with a title and description would help users understand what's going on here.

Here's what I got so far:

![screenshot from 2018-04-23 10 55 48](https://user-images.githubusercontent.com/611168/39141607-7f0d819a-46e5-11e8-9eb1-9143ec1301cd.png)
![screenshot from 2018-04-23 10 55 57](https://user-images.githubusercontent.com/611168/39141608-8040362a-46e5-11e8-8c77-5eb62ea1043b.png)

**Comment by WatchMkr** [comment]
We are telling the user to set a name even if we preseed it. It makes me think I should know the name or that it matters. Is it completely arbitrary? Is there any value in the user choosing the name of the volume? If not I don't think it should be there at all.

**Comment by cassidyjames** [comment]
@WatchMkr we discussed it a bit here in Carson and in the elementary Slack. The consensus seemed to be [simplifying that copy a little bit](https://user-images.githubusercontent.com/611168/39154029-2649c6ac-470a-11e8-878d-38147ee1f101.png), but still allowing users to set it if they are managing multiple LUKS volumes.

The reason being, this name will persist to the installed system. If a user has multiple LUKS partitions, they _probably_ don't want `data_1234`, `data_5678`, etc. random devices in their end system. I also considered an "Advanced" expander with the name behind it, but that felt unnecessary for only one option.

**Comment by cassidyjames** [comment]
I'm open to better copy, but I don't think we can completely get rid of the field.
